name: Deploy Bunny App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd bunny
          npm ci

      - name: Build app
        run: |
          cd bunny
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bunny/dist
          publish_branch: gh-pages
          force_orphan: true

      - name: Add deployment URL to summary
        run: |
          echo "### 🚀 Deployed to: https://gdunn.github.io/rogue-bunny/" >> $GITHUB_STEP_SUMMARY
        shell: bash
